### ISSUE TITLE
My queries on the Integration.

### ISSUE THREAD

**Issue by DevarajKR** [newrelic/newrelic-snowflake-integration#21]
I have done the integration & I have below questions 

1. I want to run all the queries provided by this integration every hour and i added my custom queries/metrics and i want to run those every 5/10 mins, how do i do that and what changes are required in the **flex-snowflake-linux.yml**
( both out of the box queries and custom queries are executing to dev snowflake account)

2. how do i add my prod snowflake account to pull the prod snowflake metrics in the file **flex-snowflake-linux.yml**

**Comment by Devaraj234** [comment]
@alexkroman

**Comment by matewilk** [comment]
Hey @Devaraj234 

You need to edit [this](https://github.com/newrelic/newrelic-snowflake-integration/blob/main/flexConfigs/flex-snowflake-linux.yml#L4) line in the config file.

Here is the [link](https://github.com/newrelic/nri-flex/blob/master/docs/README.md) to the Flex documentation you might want to familiarise yourself with if you want to have more control over various Flex properties.
This [page](https://github.com/newrelic/nri-flex/blob/master/docs/basics/configure.md) might be particularly useful to start with.

Hope this helps
