### ISSUE TITLE
Key/Pair Authentication does not work with 'incorrect password' error

### ISSUE THREAD

**Issue by PoeWunLee** [newrelic/newrelic-snowflake-integration#32]
## Description
Snowflake integration authentication using username and password works fine, but not when switched to key-pair authentication. The error message describes that the username and password combination is not correct, which may have indicated that despite setting the useKeyPairAuth: true and specifying the p8 key file, the key-pair auth method is not used in the node.js driver internally.

## Steps to Reproduce
1. Install snowflakeintegration-win.exe in integrations.d>script folder
2. Entered obfuscated credentials in config.yml in integrations.d>script folder with username and password as auth method (i.e. useKeyPairAuth=false)
![image](https://user-images.githubusercontent.com/64348704/172278581-1c6cec25-917a-42c1-9897-1ee076083a20.png)
3. Used dummy query (e.g. select * from snowflake.account_usage.tables limit 5) as per flex config described here: https://github.com/newrelic/newrelic-snowflake-integration/blob/main/flexConfigs/flex-snowflake-windows.yml (succeeded)
4. Repeated step 3 but with useKeyPairAuth=true in config.yml (failed)
![image](https://user-images.githubusercontent.com/64348704/172279416-bcb90cb4-9b72-49c3-9978-9ad1b66af72f.png)

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
Expected payload results returned. Expect to be the same payload result  as when using username and password auth method.
![image](https://user-images.githubusercontent.com/64348704/172278889-b927d530-5dbd-424f-9bfd-9a4744404de9.png)

The following is what was returned instead when switched to key-pair auth
![image](https://user-images.githubusercontent.com/64348704/172279681-154c9489-fb4a-48f6-836c-2a8c9f9e572e.png)

## Your Environment
Windows Virtual Machine on Azure

**Comment by matewilk** [comment]
Hi @PoeWunLee 

By the looks of it, when you want to use the `useKeyPairAuth = true` option, you also need to supply the configuration with the [privateKeyPath](https://github.com/newrelic/newrelic-snowflake-integration/blob/main/snowflake.js#L81).

So your `credentials` configuration should look like this:

```js
credentials:
    useKeyPairAuth: true
    privateKeyPath: "path to the key file"
    account: "account"
    username: "user"
    role: "role"
    warehouse: "warehouse"
```

**Comment by matewilk** [comment]
Sorry @PoeWunLee, scrap the above, I've just noticed [this](https://github.com/newrelic/newrelic-snowflake-integration/blob/main/snowflake.js#L85) comment, so it actually suggests, that this type of authentication is not actually supported yet
