### ISSUE TITLE
Can't parse Environment Variables used in flex config

### ISSUE THREAD

**Issue by ron-joe** [newrelic/newrelic-snowflake-integration#49]
When trying to run the queries listed in the flex config, the variables defined in the snowflake.env file such as $$NEWRELIC_SNOWFLAKE_HOME are not being parsed with the error message stating "Integration stderr (not parsed)".
Hence causing the integration to fail.

Error details:
time="2023-03-17T04:42:31Z" level=debug msg="Integration stderr (not parsed)." component=integrations.runner.Runner integration_name=nri-flex line="time=\"2023-03-17T04:42:31Z\" level=debug msg=\"command: failed\
" context_err= err=\"exit status 127\" exec=\"$$NEWRELIC_SNOWFLAKE_HOME/snowflakeintegration-linux $$NEWRELIC_SNOWFLAKE_HOME/config.yaml $$NEWRELIC_SNOWFLAKE_HOME/queries/query_history_detail.sql\" suggestion=\"i
f you are handling this error case, ignore\"" runner_uid=80589e3990

Config:
snowflake.env file containing the following variable:
NEWRELIC_SNOWFLAKE_HOME=/newrelic-snowflake-integration

**Comment by ajaybalajoshi** [comment]
Facing same issue, agent is installed using tar and all the configuration defined and it looks as below 

Please find the details related to NEWRELIC_SNOWFLAKE_HOME,
 
I have added below line in /etc/systemd/system/newrelic-infra.service,
 
EnvironmentFile=/opt/newrelic-infra-agent/custom-integrations/newrelic-snowflake-integration/snowflake.env
 
And contents of snowflake.env looks as below.
 
NEWRELIC_SNOWFLAKE_HOME=/opt/newrelic-infra-agent/custom-integrations/newrelic-snowflake-integration/
SNOW_ACCOUNT=ACCOUNTNAME
SNOW_USER=USERNAME
SNOW_PWD=PASSWORD
SNOW_ROLE=ROLENAME

ERROR Message:
$$NEWRELIC_SNOWFLAKE_HOME/snowflakeintegration-linux $$NEWRELIC_SNOWFLAKE_HOME/config.yaml $$NEWRELIC_SNOWFLAKE_HOME/queries/warehouse_load_history.sql

**Comment by ajaybalajoshi** [comment]
I tried it but still it is not working when i export the variable i am receiving below error. 
`/bin/sh: 1: 1489853NEWRELIC_SNOWFLAKE_HOME/snowflakeintegration-linux: not found
