### ISSUE TITLE
Allow warehouse to be specified in config.yaml

### ISSUE THREAD

**Issue by nedl86** [newrelic/newrelic-snowflake-integration#9]
## Summary

Integration only currently works if the specified user has a default warehouse configured in Snowflake, and some of the queries (the warehouse-level ones) will only be executed for that user's default warehouse. This forces creation of multiple users - one per warehouse - which complicates setup and ongoing management.

## Desired Behavior

Integration should run when the user _doesn't_ have a default warehouse set, and should be able to retrieve metrics for multiple warehouses without needing to create multiple users.

## Possible Solution

Snowflake's Node.js driver allows for the `warehouse` to be specified when the connection is established: https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#additional-connection-options

Integration should allow a session-level `warehouse` to be specified in the `config.yaml` file and passed through to the Snowflake Node.js driver, thereby allowing creation of multiple config files (one per warehouse) which can then be specified in the Flex configs.

## Additional context

It's unusual for a monitoring user to have a default warehouse set in the first place, and it's unappealing to create multiple monitoring users (one for each warehouse).

**Comment by danifitz** [comment]
@nedl86 Fixed by https://github.com/newrelic/newrelic-snowflake-integration/releases/tag/v0.1.7
